* Introduction
There is a stub [[file:~/.emacs][.emacs file]] which uses org-babel to load this file.

Inspiration from the approach at [[https://github.com/dbr/dotemacs][dbr/dotemacs]] as found in a [[http://www.reddit.com/r/emacs/comments/12pgtg/restarting_from_scratch/][reddit thread]].

* Package Management
** Package setup
Some of this is done in .emacs now, keeping here for documentation.
#+begin_src emacs-lisp :tangle no
  ;(require 'package)
  ;(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
  ;(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
  ;(package-initialize)

  ;(when (not package-archive-contents)
  ;  (package-refresh-contents))
#+end_src
** Package install
And now for automatic package installation:
#+begin_src emacs-lisp
  (defun ensure-pkgs (packages) (mapc (lambda (pkg) (or (package-installed-p pkg) (package-install pkg))) packages))
  
  (ensure-pkgs '(melpa
                 ibuffer-vc
                 ido-ubiquitous
                 dired+
                 ace-jump-mode
                 expand-region
                 multiple-cursors
                 sunrise-commander
                 magit
                 magit-commit-training-wheels
                 org-plus-contrib))
#+end_src
* Behavior Tweaks
** cl
#+begin_src emacs-lisp
(require 'cl)
#+end_src

** Server mode
#+begin_src emacs-lisp
(server-start)
#+end_src
** Chdir to ~ 
Depending on how the emacs daemon is started, the current directory is less than ideal.

#+begin_src emacs-lisp
  (cd (expand-file-name "~/"))
#+end_src

** Disable backups
#+begin_src emacs-lisp
  (setq backup-inhibited t)
  (setq auto-save-default nil)
#+end_src
** Speed Tweaks
#+begin_src emacs-lisp
(setq font-lock-verbose nil)
(setq vc-handled-backends '(Git))
;(setq jit-lock-defer-time 0.05)
#+end_src
** Modern Sentences
#+begin_src emacs-lisp
(setq sentence-end-double-space nil)
#+end_src
** Zap chars
I prefer the vim style zap.  Leaving old one on M-Z.

#+begin_src emacs-lisp
(autoload 'zap-up-to-char "misc"
  "Kill up to, but not including ARGth occurrence of CHAR.")
(global-set-key (kbd "M-z") 'zap-up-to-char)
(global-set-key (kbd "M-Z") 'zap-to-char)
#+end_src
** Save point position between sessions
#+begin_src emacs-lisp
(require 'saveplace)
(setq-default save-place t)
(setq save-place-file (expand-file-name ".places" user-emacs-directory))
#+end_src
** Mouse support on terminal
#+BEGIN_SRC emacs-lisp
  (unless window-system (xterm-mouse-mode))
#+END_SRC
* Interface
** Mac command modifiers
#+begin_src emacs-lisp
(setq mac-command-modifier 'hyper)
(setq mac-option-modifier 'meta)
(setq mac-fn-modifier 'super)
#+end_src
** Font
The same font can have different names on each platform.
+begin_src emacs-lisp
  (defun my-font ()  
    (case window-system
      ('x  (set-frame-font " 18"))))
  (my-font)
+end_src

** Minimal Window Decor
#+begin_src emacs-lisp
(setq inhibit-splash-screen t)
(menu-bar-mode 0)
(tool-bar-mode 0)
(scroll-bar-mode 0)
#+end_src

** Color scheme
I'm using a forked solarzied version which supports terminals with 256 colors, but with the normal 16 configured in
the solarized theme.  The available packages currently use the 256 color version, which isn't as accurate.

#+begin_src emacs-lisp
(add-to-list 'custom-theme-load-path (expand-file-name "~/.emacs.d/non-elpa/solarized"))
(load-theme 'solarized-dark t)
#+end_src
** Don't bother me as much
#+begin_src emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
#+end_src
* Custom Functionality
** Jump to .emacs
#+begin_src emacs-lisp
;; Jump to .emacs
(defun my-edit-dot-emacs ()
  (interactive)
  (find-file "~/.emacs.d/init.org"))
(global-set-key (kbd "C-c e") 'my-edit-dot-emacs)
#+end_src

* Module Configuration
** Helm
#+BEGIN_SRC emacs-lisp
  (ensure-pkgs '(helm))
  (require 'helm-config)
#+END_SRC
** Tramp
Fix too long TMPDIR:
#+begin_src emacs-lisp
(setenv "TMPDIR" "/tmp")
#+end_src

Default method:
#+begin_src emacs-lisp
  ;;(setq tramp-default-method "ssh")
#+end_src

** IDO Everywhere
#+begin_src emacs-lisp
(ido-mode t)
(ido-ubiquitous-mode)
#+end_src

** Ibuffer
#+begin_src emacs-lisp
  (global-set-key (kbd "C-x C-b") 'ibuffer)
  (autoload 'ibuffer "ibuffer" "List buffers." t)
  (eval-after-load 'ibuffer
    '(progn
       (add-hook 'ibuffer-hook
                 (lambda ()
                   (ibuffer-vc-set-filter-groups-by-vc-root)
                   (unless (eq ibuffer-sorting-mode 'alphabetic)
                     (ibuffer-do-sort-by-alphabetic))))
       (setq ibuffer-formats
             '((mark modified read-only vc-status-mini " "
                     (name 18 18 :left :elide)
                     " "
                     (size 9 -1 :right)
                     " "
                     (mode 16 16 :left :elide)
                     " "
                     (vc-status 16 16 :left)
                     " "
                     filename-and-process)))))
#+end_src
** Window Management
#+begin_src emacs-lisp
(when (fboundp 'winner-mode)
  (winner-mode 1)
  (global-set-key (kbd "<mouse-8>") 'winner-undo)
  (global-set-key (kbd "<mouse-9>") 'winner-redo))
#+end_src
** Cua Selection mode, but no C-x or C-c
#+begin_src emacs-lisp
(cua-selection-mode t)
#+end_src
** Expand Region
#+begin_src emacs-lisp
(global-set-key (kbd "C-=") 'er/expand-region)
(global-set-key (kbd "M-=") 'er/expand-region)
#+end_src
** Multiple Cursors
#+begin_src emacs-lisp
(global-set-key (kbd "C-c C-SPC") 'mc/edit-lines)
(global-set-key (kbd "M-]") 'mc/mark-next-like-this)
;; (global-set-key (kbd "C-c C-e") 'mc/edit-ends-of-lines)
;; (global-set-key (kbd "C-c C-a") 'mc/edit-beginnings-of-lines)
#+end_src
*** Rectangular region mode
#+begin_src emacs-lisp
;; (global-set-key (kbd "C-c RET") 'set-rectangular-region-anchor)
#+end_src
*** Mark More like this
These are available with an active region.
#+begin_src emacs-lisp
;; (define-key region-bindings-mode-map "a" 'mc/mark-all-like-this)
;; (define-key region-bindings-mode-map "p" 'mc/mark-previous-like-this)
;; (define-key region-bindings-mode-map "n" 'mc/mark-next-like-this)
;; (define-key region-bindings-mode-map "m" 'mc/mark-more-like-this-extended)
#+end_src

#+begin_src emacs-lisp :noweb-ref my-pkg :exports none :tangle no
;;  (:name region-bindings-mode
;;         :type github
;;         :pkgname "fgallina/region-bindings-mode"
;;         :features region-bindings-mode
;;         :after (progn (region-bindings-mode-enable)))
#+end_src
** Ace Jump Mode
#+begin_src emacs-lisp
(ensure-pkgs '(ace-jump-mode))
(define-key global-map (kbd "C-c SPC") 'ace-jump-mode)
#+end_src
** Sunrise Commander
*** Bindings
#+begin_src emacs-lisp
  ;; F11 for sunrise commander
  (global-unset-key (kbd "<f11>"))
  (global-set-key (kbd "<f11>") 'sunrise)
  ;; Safe alternative
  (global-set-key (kbd "C-c s") 'sunrise)
#+end_src
** Magit
*** Bindings
#+begin_src emacs-lisp
;; F12 for magit
(global-unset-key (kbd "<f12>"))
(global-set-key (kbd "<f12>") 'magit-status)
;; Safe alternative
(global-set-key (kbd "C-c g") 'magit-status)
#+end_src
*** Training wheels
#+BEGIN_SRC emacs-lisp
(require 'magit-commit-training-wheels)
(ad-activate 'magit-log-edit-commit)
#+END_SRC
** Battery life in mode line
#+begin_src emacs-lisp
;; (setq battery-mode-line-format "[%b%p%% %t]")
;; (display-battery-mode)
#+end_src

** Ack and Ag
#+BEGIN_SRC emacs-lisp
    (ensure-pkgs '(ack-and-a-half ag wgrep-ag))
    (setq ag-highlight-search t
          ag-reuse-buffers 't)
#+END_SRC
** Dired and Dired Extensions
#+begin_src emacs-lisp
  (require 'dired-x)
  (setq dired-omit-files-p t)
  (add-hook 'dired-mode-hook (lambda () (dired-omit-mode)))
#+end_src

* Programming modes
** Indent settings
Don't use tabs, default to 4 spaces.
#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
(setq tab-width 4)
(defvaralias 'c-basic-offset 'tab-width)
(defvaralias 'cperl-indent-level 'tab-width)
#+end_src
** Lisps
*** Paredit
#+begin_src emacs-lisp
  ;; ;; Paredit
  ;; (mapc (lambda (mode)
  ;;         (let ((hook (intern (concat (symbol-name mode)
  ;;                                     "-mode-hook"))))
  ;;           (add-hook hook (lambda () (paredit-mode +1)))))
  ;;       '(emacs-lisp lisp inferior-lisp))
#+end_src
*** Elisp slime nav
Adds M-* and M-, to elisp buffers.
#+begin_src emacs-lisp :noweb-ref my-pkg :exports none :tangle no
  ;; (:name elisp-slime-nav
  ;;        :type github
  ;;        :pkgname "purcell/elisp-slime-nav")
#+end_src

#+begin_src emacs-lisp
  ;; (add-hook 'emacs-lisp-mode-hook (lambda () (elisp-slime-nav-mode t)))
#+end_src

** Projectile
Possible fit for project management.
#+begin_src emacs-lisp
;(setq projectile-enable-caching t)
;(projectile-global-mode)
#+end_src
** Flymake
#+begin_src emacs-lisp
;; (require 'flymake-cursor)
#+end_src

#+begin_src emacs-lisp :noweb-ref my-pkg :exports none :tangle no
;;  (:name flymake-shell
;;         :type github
;;         :pkgname "purcell/flymake-shell")
#+end_src
** Tags
#+begin_src emacs-lisp
(setq tags-revert-without-query t)
#+end_src
** Yasnippet
#+begin_src emacs-lisp
  (ensure-pkgs '(yasnippet))
  (yas-global-mode 1)
  (yas-load-directory "~/.emacs.d/snippets" t)
#+end_src

*** Fold-Dwim-Org compatibility shim
#+begin_src emacs-lisp
(defalias 'yas/snippets-at-point 'yas--snippets-at-point) ;; fold-dwim-org compatibility
(setq fold-dwim-org/trigger-keys-block (list [tab] [lefttab] [(control tab)]))
#+end_src
** smartparens
modern lightweight smart parens/auto-insert/wrapping package for Emacs
#+begin_src emacs-lisp :noweb-ref my-pkg :exports none :tangle no
  ;; (:name smartparens
  ;;        :type github
  ;;        :pkgname "Fuco1/smartparens"
  ;;        :depends dash
  ;;        :feature smartparens
  ;;        :after)
#+end_src

#+begin_src emacs-lisp
;;  (smartparens-global-mode t)

  ;;; key binds
;;  (define-key sp-keymap (kbd "C-M-f") 'sp-forward-sexp)
;;  (define-key sp-keymap (kbd "C-M-b") 'sp-backward-sexp)
;;  (define-key sp-keymap (kbd "C-M-d") 'sp-down-sexp)
;;  (define-key sp-keymap (kbd "C-M-a") 'sp-backward-down-sexp)
;;  (define-key sp-keymap (kbd "C-M-e") 'sp-up-sexp)
;;  (define-key sp-keymap (kbd "C-M-u") 'sp-backward-up-sexp)
;;  (define-key sp-keymap (kbd "C-M-n") 'sp-next-sexp)
;;  (define-key sp-keymap (kbd "C-M-p") 'sp-previous-sexp)
;;  (define-key sp-keymap (kbd "C-M-k") 'sp-kill-sexp)
;;  (sp-add-ban-insert-pair-in-string "'")
#+end_src
*** dash
modern list library
#+begin_src emacs-lisp :noweb-ref my-pkg :exports none :tangle no
  ;; (:name dash
  ;;        :type github
  ;;        :pkgname "magnars/dash.el")
#+end_src

** Groovy
#+begin_src emacs-lisp
  (ensure-pkgs '(groovy-mode))
  (autoload 'groovy-mode "groovy-mode" "Major mode for editing Groovy code." t)
  (add-to-list 'auto-mode-alist '("\.groovy$" . groovy-mode))
  (add-to-list 'interpreter-mode-alist '("groovy" . groovy-mode))
  (add-to-list 'auto-mode-alist '("\.gradle$" . groovy-mode))
  
  ;;; make Groovy mode electric by default.
  (add-hook 'groovy-mode-hook
            '(lambda ()
               (require 'groovy-electric)
               (setq tab-width 2)
               (groovy-electric-mode)))
#+end_src

** Imenu
#+begin_src emacs-lisp
  (ensure-pkgs '(imenu-anywhere))
  (setq-default imenu-generic-expression '(nil))
  (global-set-key (kbd "C-.") 'imenu-anywhere)
  
  ;; Add a mark to pop back to
  (defadvice imenu-anywhere (before push-mark activate)
    (push-mark))
#+end_src
** Python!
Use elpy, and tweak indentation.
#+begin_src emacs-lisp
  (ensure-pkgs '(yasnippet flymake-cursor elpy))
  
  (elpy-enable)
  (elpy-use-ipython)
  
  (add-hook 'python-mode-hook
            (lambda ()
              (setq tab-width 2)
              (setq python-indent 2)
              (add-hook 'before-save-hook 'delete-trailing-whitespace nil t)))
#+end_src

* Org-mode Setup
** Require
#+begin_src emacs-lisp
(require 'org)
;(require 'org-protocol)
#+end_src

** Configure
 ; (setq org-hide-leading-stars t
     ;   org-completion-use-ido t
     ;   org-outline-path-complete-in-steps nil
     ;   org-enforce-todo-checkbox-dependencies t
     ;   org-enforce-todo-dependencies t
     ;   org-special-ctrl-a/e t
     ;   org-special-ctrl-k t
     ;   org-yank-adjusted-subtrees t
     ;   org-startup-indented t
     ;   org-use-fast-todo-selection t
     ;   org-directory "~/org"
     ;   org-default-notes-file (concat org-directory "/notes.org")
     ;   org-mobile-directory "~/CloudStation/mobileorg"
     ;   org-mobile-creating-agendas t;

        org-src-window-setup 'current-window
        org-src-fontify-natively t

        org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "STARTED(s)" "|" "DONE(d!/!)")
          (sequence "WAITING(w@/!)" "SOMEDAY(S!)" "|" "CANCELLED(c@/!)"))
  
  
        org-capture-templates
        '(("e" "Capture email" entry (file "inbox.org")
           "* %^{Title}\nSource: %a\n%i")
          ("t" "todo" entry (file "inbox.org")
           "* TODO %?\n%U\n%a\n  %i" :clock-in t :clock-resume t)
          ("T" "todo, sourceless" entry (file "inbox.org")
           "* TODO %?\n%U\n  %i" :clock-in t :clock-resume t)
          ("h" "Habit" entry (file "inbox.org")
           "* NEXT %?\n%U\n%a\nSCHEDULED: %t .+1d/3d\n:PROPERTIES:\n:STYLE: habit\n:REPEAT_TO_STATE: NEXT\n:END:\n  %i")
          ("w" "org-protocol" entry (file "inbox.org")
           "* TODO Review %c\n%U\n  %i" :immediate-finish t))
  
        org-refile-targets '((nil :maxlevel . 9)
                             (org-agenda-files :maxlevel . 9))
        org-refile-use-outline-path t
        org-refile-allow-creating-parent-nodes (quote confirm)
  
        ;; For better sunset calc
        calendar-latitude 37.662 
        calendar-longitude -121.874
        calendar-location-name "Pleasanton, CA"
        org-mobile-files-exclude-regexp "calendar")

** Bindings
*** Capture
#+begin_src emacs-lisp
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)
#+end_src

*** Fast Nav

  ;; From http://orgmode.org/worg/org-hacks.html
  (defun ded/org-show-next-heading-tidily ()
    "Show next entry, keeping other entries closed."
    (if (save-excursion (end-of-line) (outline-invisible-p))
        (progn (org-show-entry) (show-children))
      (outline-next-heading)
      (unless (and (bolp) (org-on-heading-p))
        (org-up-heading-safe)
        (hide-subtree)
        (error "Boundary reached"))
      (org-overview)
      (org-reveal t)
      (org-show-entry)
      (show-children)))
  
  (defun ded/org-show-previous-heading-tidily ()
    "Show previous entry, keeping other entries closed."
    (let ((pos (point)))
      (outline-previous-heading)
      (unless (and (< (point) pos) (bolp) (org-on-heading-p))
        (goto-char pos)
        (hide-subtree)
        (error "Boundary reached"))
      (org-overview)
      (org-reveal t)
      (org-show-entry)
      (show-children)))
  
  (setq org-use-speed-commands t)
  (setq org-speed-commands-user
        '(("n" . ded/org-show-next-heading-tidily)
          ("p" . ded/org-show-previous-heading-tidily)
          ("J" . org-clock-goto)))

** Org Links

  (setq org-link-abbrev-alist
         '(("jira" . "https://jira.@workplace@.com/browse/")
           ("review" . "https://crucible.@workplace@.com/cru/")
          ))


*** Defunct

  ;; (setq org-link-abbrev-alist
  ;;        '(("jira" . "https://jira.@workplace@.com/browse/")
  ;;      ;;("devdrop" . "https://env.@xyzzy@.com:9030/oms/fx/search.flex?q=%s")
  ;;      ;;("work" . "http://localhost:4444/work/fx/search.flex?q=%s")
  ;;      ;;("work" . "https://dev.@xyzzy@.com/work/fx/search.flex?q=%s")
  ;;      ;;("work" . "https://dev.@xyzzy@.com/oms/fx/search.flex?q=%s")
  ;;      ))
  
  ;;  (defun my-org-make-ids-links ()
  ;;    (interactive)
  ;;    (save-excursion
  ;;      (query-replace-regexp " \\([0-9]+[$.][0-9]+\\)" " [[devdrop:\\1][\\1]]")))

** Org-mobile
*** Schedule

(defun my-org-mobile-pull/push ()
  (interactive)
  (org-mobile-pull)
  (org-mobile-push))


(run-at-time t 900 'my-org-mobile-pull/push)

** Agenda commands

(setq org-agenda-custom-commands
      '(("o" "Overview"
	 ((tags-todo "+home")
	  (tags-todo "+work")
	  (tags-todo "-home-work")
	  (agenda ""))
	 ((org-agenda-ndays 1)))
	("h" tags-todo "+home")
	("w" tags-todo "+work")))

** Org-Velocity
+begin_src emacs-lisp
(require 'org-velocity)

(global-set-key (kbd "C-c v") 'org-velocity-read)
(setq org-velocity-bucket "~/org/velocity.org")
(setq org-velocity-always-use-bucket t)
(setq org-velocity-exit-on-match t)
+end_src
** Org and YAS (Defunct)

;; (defun yas/org-very-safe-expand ()
;;   (let ((yas/fallback-behavior 'return-nil)) (yas/expand)))

;; (add-hook 'org-mode-hook
;; 	  (lambda ()
;; 	    (make-variable-buffer-local 'yas/trigger-key)
;; 	    (setq yas/trigger-key [tab])
;; 	    (add-to-list 'org-tab-first-hook 'yas/org-very-safe-expand)
;; 	    (define-key yas/keymap [tab] 'yas/next-field)))


** Org Mode notifications

(require 'appt)
(setq appt-message-warning-time 15
      appt-display-mode-line t
      appt-display-format 'window)
(appt-activate 1)
(display-time)

(org-agenda-to-appt t)
(add-hook 'org-finalize-agenda-hook 'org-agenda-to-appt)


** Stay on task (Idle display of Agenda)

  ;; From http://article.gmane.org/gmane.emacs.orgmode/23047
  (defun jump-to-org-agenda ()
    (interactive)
    (let ((buf (get-buffer "*Org Agenda*"))
          wind)
      (if buf
          (if (setq wind (get-buffer-window buf))
              (select-window wind)
            (if (called-interactively-p)
                (progn
                  (select-window (display-buffer buf t t))
                  (org-fit-window-to-buffer)
                  ;; (org-agenda-redo)
                  )
              (with-selected-window (display-buffer buf)
                (org-fit-window-to-buffer)
                ;; (org-agenda-redo)
                )))
        (call-interactively 'org-agenda-list)))
    ;;(let ((buf (get-buffer "*Calendar*")))
    ;;  (unless (get-buffer-window buf)
    ;;    (org-agenda-goto-calendar)))
    )
  (let ((timer (timer-create)))
    (timer-set-function timer 'jump-to-org-agenda)
    (timer-set-idle-time timer 300 t)
    (timer-activate-when-idle timer nil))
  ;;(run-with-idle-timer 300 t 'jump-to-org-agenda)


** org contacts

(setq org-contacts-files '("~/org/contacts.org"))


** org bullets

  (:name org-bullets
         :type github
         :pkgname "sabof/org-bullets"
         :features org-bullets
         :after (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))



  (setq org-bullets-bullet-list '("◉" "○" "•" "★"))

** Export
*** Dark backgrounds for code blocks

;; (setq org-export-html-style
;;       "<style type=\"text/css\">
;; <!--/*--><![CDATA[/*><!--*/
;; pre.src { color: #f6f3e8 !important; background-color: #242424 !important; }
;; /*]]>*/-->
;; </style>")

* Mail
** SMTP

(setq starttls-use-gnutls t
      send-mail-function 'smtpmail-send-it
      message-send-mail-function 'smtpmail-send-it
      smtpmail-starttls-credentials '(("pod51011.outlook.com" 587 nil nil))
      smtpmail-auth-credentials (expand-file-name "~/.authinfo")
      smtpmail-default-smtp-server "pod51011.outlook.com"
      smtpmail-smtp-server "pod51011.outlook.com"
      smtpmail-smtp-service 587
      smtpmail-debug-info t)
(require 'smtpmail)

** Mu4E


  (add-to-list 'load-path "/usr/local/Cellar/mu/0.9.9/share/emacs/site-lisp/mu4e")
  (when  (require 'mu4e nil t)
    (setq mu4e-org-contacts-file "~/org/contacts.org"
          mu4e-maildir       "~/Maildir/Workday"   ;; top-level Maildir
          mu4e-sent-folder   "/sent"       ;; where do i keep sent mail?
          mu4e-drafts-folder "/Drafts"     ;; where do i keep half-written mail?
          mu4e-trash-folder  "/Trash"     ;; where do i move deleted mail?
          user-mail-address "@first@.@last@@@workplace@.com"
          user-full-name "@First@ @Last@"
          mail-user-agent 'mu4e-user-agent
          mu4e-get-mail-command "pkill -SIGUSR1 offlineimap"
          ;;     mu4e-html2text-command "html2text -nobs -utf8 -width 72"
          mu4e-html2text-command "~/bin/my-html2text"
          mu4e-mu-binary "/usr/local/bin/mu"
          )
    (add-to-list 'mu4e-headers-actions
                 '("org-contact-add" ?o mu4e-action-add-org-contact) t)
    (add-to-list 'mu4e-view-actions
                 '("org-contact-add" ?o mu4e-action-add-org-contact) t)
    (global-set-key (kbd "C-c m") 'mu4e)
  
    ;; Patch in a maildirproc button.
    (defun my-mu4e-maildirproc ()
      (interactive)
      (let ((mu4e-get-mail-command "maildirproc --once"))
        (mu4e-update-mail-show-window)))
    (defun my-add-maildirproc-mu4e-command ()
      (let ((buf (get-buffer-create mu4e~main-buffer-name))
            (inhibit-read-only t))
        (with-current-buffer buf
          (insert
           (mu4e~main-action-str "\t* [m]aildirproc\n" 'my-mu4e-maildirproc)))))
    (define-key mu4e-main-mode-map "m" 'my-mu4e-maildirproc)
    (defadvice mu4e~main-view (after my-ad-maildirproc activate)
      (my-add-maildirproc-mu4e-command)))

* ERC
Using bouncer.
#+begin_src emacs-lisp
    (load-file (expand-file-name "~/.emacs.d/secrets.el"))
    (defun my-erc () 
      (interactive)
      (erc
        :server "localhost"
        :port "6667"
        :nick my-erc-name 
        :password my-erc-password))
#+end_src

* Custom File
#+begin_src emacs-lisp
(setq custom-file (expand-file-name "~/.emacs.d/custom.el"))
(load custom-file)
#+end_src
